const busNumberBasedStops = {
    "102": [
        "BACKBAY BUS DEPOT",
        "CSMT BUS STATION",
        "MARINE LINES BUS STATION",
        "BALLARD PIER BUS STOP",
        "PRIYADARSHANI PARK BUS STOP",
        "WADALA BUS DEPOT",
        "MAHIM BUS DEPOT",
        "KHODADAD CIRCLE DADAR EAST",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "AGARKAR CHOWK BUS STOP ANDHERI EAST"
    ],
    "103": [
        "AGARKAR CHOWK BUS STOP ANDHERI EAST",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "GHATKOPAR BUS DEPOT",
        "VIKHROLI BUS DEPOT",
        "KURLA NEHRU NAGAR BUS DEPOT",
        "CHEMBUR BUS DEPOT",
        "SAKI NAKA BUS STOP"
    ],
    "104": [
        "AGARKAR CHOWK BUS STOP ANDHERI EAST",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "SANTACRUZ BUS DEPOT",
        "VILE PARLE BUS STAND",
        "OSHIWARA BUS DEPOT",
        "VIRWANI ESTATE GOREGAON EAST BUS STOP",
        "BORIVALI WEST BUS STATION"
    ],
    "105": [
        "SAKI NAKA BUS STOP",
        "KURLA NEHRU NAGAR BUS DEPOT",
        "CHEMBUR BUS DEPOT",
        "MULUND WEST BUS DEPOT",
        "KANJURMARG WEST BUS STATION",
        "VILE PARLE BUS STAND",
        "SANTACRUZ BUS DEPOT"
    ],
    "106": [
        "BACKBAY BUS DEPOT",
        "CSMT BUS STATION",
        "MARINE LINES BUS STATION",
        "BALLARD PIER BUS STOP",
        "WADALA BUS DEPOT",
        "MAHIM BUS DEPOT",
        "KHODADAD CIRCLE DADAR EAST",
        "MULUND WEST BUS DEPOT",
        "KANJURMARG WEST BUS STATION"
    ],
    "601": [
        "KANJURMARG WEST BUS STATION",
        "MULUND WEST BUS DEPOT",
        "WADALA BUS DEPOT",
        "MAHIM BUS DEPOT",
        "KHODADAD CIRCLE DADAR EAST",
        "CSMT BUS STATION",
        "MARINE LINES BUS STATION",
        "BALLARD PIER BUS STOP",
        "BACKBAY BUS DEPOT"
    ],
    "501": [
        "SANTACRUZ BUS DEPOT",
        "VILE PARLE BUS STAND",
        "MULUND WEST BUS DEPOT",
        "KANJURMARG WEST BUS STATION",
        "KURLA NEHRU NAGAR BUS DEPOT",
        "CHEMBUR BUS DEPOT",
        "SAKI NAKA BUS STOP"
    ],
    "401": [
        "BORIVALI WEST BUS STATION",
        "OSHIWARA BUS DEPOT",
        "VIRWANI ESTATE GOREGAON EAST BUS STOP",
        "SANTACRUZ BUS DEPOT",
        "VILE PARLE BUS STAND",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "AGARKAR CHOWK BUS STOP ANDHERI EAST"
    ],
    "301": [
        "SAKI NAKA BUS STOP",
        "KURLA NEHRU NAGAR BUS DEPOT",
        "CHEMBUR BUS DEPOT",
        "GHATKOPAR BUS DEPOT",
        "VIKHROLI BUS DEPOT",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "AGARKAR CHOWK BUS STOP ANDHERI EAST"
    ],
    "201": [
        "AGARKAR CHOWK BUS STOP ANDHERI EAST",
        "RANI LAXMIBAI BUS STATION SION",
        "BANDRA WEST BUS DEPOT",
        "PRABODHANKAR THACKRAY UDAYAN SEWRI",
        "WADALA BUS DEPOT",
        "MAHIM BUS DEPOT",
        "KHODADAD CIRCLE DADAR EAST",
        "PRIYADARSHANI PARK BUS STOP",
        "CSMT BUS STATION",
        "MARINE LINES BUS STATION",
        "BALLARD PIER BUS STOP",
        "BACKBAY BUS DEPOT"
    ]
}
export default busNumberBasedStops;